summarization/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import summarizer.urls as summarizer

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(summarizer,namespace='summarizer')),
]

summarizer/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^(?P<id>\w{0,50})/$', show_summarize, name='show_summarize'),
]

summarizer/models.py
from django.db import models

# Create your models here.
class Menteri(models.Model):
	nama = models.CharField(max_length=50)
	foto = models.CharField(max_length=300)

	def __str__(self):
		return self.nama
		
	def getUnderscore(self):
		name_with_underscore = self.nama.replace(" ", "_")
		return name_with_underscore

summarizer/views.py
from django.shortcuts import render
from .models import Menteri
from .summarizer import evaluateSentenceScores

# Create your views here.
response = {}
def index(request):
	menteris = Menteri.objects.all()
	response["menteris"] = menteris

	html = "pilih-menteri.html"
	return render(request, html, response)

def show_summarize(request, id):
	menteri = Menteri.objects.get(id=id)

	response['menteri'] = menteri
	nama_underscore = menteri.getUnderscore()
	summary = evaluateSentenceScores(nama_underscore)
	response['summary'] = summary

	html = 'show-summarize.html'
	return render(request, html, response) 	

summarizer/templates/pilih-menteri.html
{% extends "summarizer/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<body>
    <h1 class="underline">Pilih Menteri yang akan di Summarize</h1>

    <div class="d-flex align-content-start flex-wrap boxy align-items-stretch">
        {% for menteri in menteris %}
            <div class="p-2 bd-highlight list-menteri ">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ menteri.foto }}" alt="Card image cap" style="height:350px;">
                    <div class="card-body">
                      <p class="card-text nama-menteri">{{menteri.nama}}</p>
                      <a href="{% url 'summarizer:show_summarize' menteri.id %}" class="btn btn-primary button">Summarize</a>
                    </div>
                  </div>
            </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

summarizer/templates/show-summarize.html
{% extends "summarizer/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<body>
  <div class="container">
    <div class="col-md-12">
      <div class="row">
          <div class="card text-white bg-dark d-inline-block col-md-12" style="margin:10px; padding:10px">
            <div class="card-header">Hasil Ringkasan</div>
              <div class="card-body" style="margin:10px;">
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-sm-8 col-md-6 col-lg-4">
                      <img src="{{ menteri.foto }}" style="width:100%; height: auto;"/>
                    </div>
                    <div class="col-sm-4 col-md-6 col-lg-8">
                      <!-- <div class="row"> -->
                        <h4 class="card-title">{{menteri.nama}}</h4>
                          <p class="card-text">{{summary}}</p>
                          <a type="button" class="btn btn-primary" href="/">Kembali</a>
                      <!-- </div> -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
              
          </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

summarizer/templates/summarizer/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Summarize Menteri">
    <meta name="author" content="{{author}}">
     <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Bootstrap Js CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <link href='https://fonts.googleapis.com/css?family=Montserrat:thin,extra-light,light,100,200,300,400,500,600,700,800' rel='stylesheet' type='text/css'>
    
    <link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
    <!-- <script src="transaksi.js"></script> -->
    <title>
      {% block title %}
      {% endblock %}
      
    </title>
  </head>

  <body style='background:linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ),url("{% static 'bendera.jpg' %}");
  filter: blur(); background-repeat: no-repeat; background-attachment: fixed; background-position: center; background-size: cover; '>
    <header>
      {% include "summarizer/partials/navbar.html" %}
    </header>

    <content>
      <div class="body-container">
        {% block content %}
        {% endblock %}
      </div>
    </content> 
      
  </body>
</html>

summarizer/templates/summarizer/partials/navbar.html
{% load staticfiles %}
{% load static %}
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <a class="nav-link" href="">Summarize Menteri Indonesia</a>
          </li>
      </ul>
  </div>
</nav>